//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiFileUploadTest.DosyAAktarim {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DosyAAktarim.TeknoserDosyaAktarimSoap")]
    public interface TeknoserDosyaAktarimSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ATTACHSAVE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResult ATTACHSAVE(MultiFileUploadTest.DosyAAktarim.RequestAttachSave RequestAttachSave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ATTACHSAVEFOLDER", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResult ATTACHSAVEFOLDER(MultiFileUploadTest.DosyAAktarim.RequestAttachSaveFOLDER RequestAttachSave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ATTACHSAVEFOLDER_NEW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResultNew ATTACHSAVEFOLDER_NEW(MultiFileUploadTest.DosyAAktarim.RequestAttachSaveFOLDER RequestAttachSave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ATTACHSAVEFOLDER_NEW_PILOT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResultNew ATTACHSAVEFOLDER_NEW_PILOT(MultiFileUploadTest.DosyAAktarim.RequestAttachSaveFOLDER RequestAttachSave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETEATTACH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResult DELETEATTACH(MultiFileUploadTest.DosyAAktarim.RequestDeleteAttach RequestDeleteAttach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MOBILEPRINTINFOREOPEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResult MOBILEPRINTINFOREOPEN(string BILDIRIMNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATEVENDORFILEID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResult UPDATEVENDORFILEID(MultiFileUploadTest.DosyAAktarim.RequestUPDATEVENDORFILEID RequestUPDATEVENDORFILEID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETEATTACH_BILDIRIMNO_AND_DOSYATIPI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResult DELETEATTACH_BILDIRIMNO_AND_DOSYATIPI(MultiFileUploadTest.DosyAAktarim.RequestDeleteBildirimAndDosyaTipi RequestDeleteBildirimAndDosyaTipi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GETATTACHIMAGE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResult GETATTACHIMAGE(MultiFileUploadTest.DosyAAktarim.RequestAttachImage RequestAttachImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GETATTACH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResult GETATTACH(MultiFileUploadTest.DosyAAktarim.RequestGetAttach RequestGetAttach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GETATTACHBULKCODE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResult GETATTACHBULKCODE(MultiFileUploadTest.DosyAAktarim.RequestGetAttachBulkCode RequestGetAttach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATEFILECOUNT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UPDATEFILECOUNT(string _ApplicationName, string BILDIRIMNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ING_ATTACHSAVEFOLDER", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResult ING_ATTACHSAVEFOLDER(MultiFileUploadTest.DosyAAktarim.RequestAttachSaveFOLDER RequestAttachSave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ING_DELETEATTACH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResult ING_DELETEATTACH(MultiFileUploadTest.DosyAAktarim.RequestDeleteAttach RequestDeleteAttach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ING_GETATTACHIMAGE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MultiFileUploadTest.DosyAAktarim.ResponseResult ING_GETATTACHIMAGE(MultiFileUploadTest.DosyAAktarim.RequestAttachImage RequestAttachImage);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestAttachSave : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bILDIRIMNOField;
        
        private byte[] aTTACHField;
        
        private int aTTACHFILESIZEField;
        
        private string aTTACHFILENAMEField;
        
        private string aTTACHFILECONTENTTYPEField;
        
        private System.DateTime rECORD_DATEField;
        
        private string oRJINALFILENAMEField;
        
        private bool iSCONTROLField;
        
        private string aTTACHDESCRIPTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BILDIRIMNO {
            get {
                return this.bILDIRIMNOField;
            }
            set {
                this.bILDIRIMNOField = value;
                this.RaisePropertyChanged("BILDIRIMNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ATTACH {
            get {
                return this.aTTACHField;
            }
            set {
                this.aTTACHField = value;
                this.RaisePropertyChanged("ATTACH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ATTACHFILESIZE {
            get {
                return this.aTTACHFILESIZEField;
            }
            set {
                this.aTTACHFILESIZEField = value;
                this.RaisePropertyChanged("ATTACHFILESIZE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ATTACHFILENAME {
            get {
                return this.aTTACHFILENAMEField;
            }
            set {
                this.aTTACHFILENAMEField = value;
                this.RaisePropertyChanged("ATTACHFILENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ATTACHFILECONTENTTYPE {
            get {
                return this.aTTACHFILECONTENTTYPEField;
            }
            set {
                this.aTTACHFILECONTENTTYPEField = value;
                this.RaisePropertyChanged("ATTACHFILECONTENTTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime RECORD_DATE {
            get {
                return this.rECORD_DATEField;
            }
            set {
                this.rECORD_DATEField = value;
                this.RaisePropertyChanged("RECORD_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ORJINALFILENAME {
            get {
                return this.oRJINALFILENAMEField;
            }
            set {
                this.oRJINALFILENAMEField = value;
                this.RaisePropertyChanged("ORJINALFILENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool ISCONTROL {
            get {
                return this.iSCONTROLField;
            }
            set {
                this.iSCONTROLField = value;
                this.RaisePropertyChanged("ISCONTROL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ATTACHDESCRIPTION {
            get {
                return this.aTTACHDESCRIPTIONField;
            }
            set {
                this.aTTACHDESCRIPTIONField = value;
                this.RaisePropertyChanged("ATTACHDESCRIPTION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestGetAttachBulkCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bULKTRANSFER_CODEField;
        
        private string aPPLICATIONNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BULKTRANSFER_CODE {
            get {
                return this.bULKTRANSFER_CODEField;
            }
            set {
                this.bULKTRANSFER_CODEField = value;
                this.RaisePropertyChanged("BULKTRANSFER_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string APPLICATIONNAME {
            get {
                return this.aPPLICATIONNAMEField;
            }
            set {
                this.aPPLICATIONNAMEField = value;
                this.RaisePropertyChanged("APPLICATIONNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestGetAttach : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bILDIRIMNOField;
        
        private string aPPLICATIONNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BILDIRIMNO {
            get {
                return this.bILDIRIMNOField;
            }
            set {
                this.bILDIRIMNOField = value;
                this.RaisePropertyChanged("BILDIRIMNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string APPLICATIONNAME {
            get {
                return this.aPPLICATIONNAMEField;
            }
            set {
                this.aPPLICATIONNAMEField = value;
                this.RaisePropertyChanged("APPLICATIONNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestAttachImage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestDeleteBildirimAndDosyaTipi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bILDIRIMNOField;
        
        private string dOSYATIPIField;
        
        private string aPPLICATIONNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BILDIRIMNO {
            get {
                return this.bILDIRIMNOField;
            }
            set {
                this.bILDIRIMNOField = value;
                this.RaisePropertyChanged("BILDIRIMNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DOSYATIPI {
            get {
                return this.dOSYATIPIField;
            }
            set {
                this.dOSYATIPIField = value;
                this.RaisePropertyChanged("DOSYATIPI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string APPLICATIONNAME {
            get {
                return this.aPPLICATIONNAMEField;
            }
            set {
                this.aPPLICATIONNAMEField = value;
                this.RaisePropertyChanged("APPLICATIONNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestUPDATEVENDORFILEID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string vENDORFILEIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VENDORFILEID {
            get {
                return this.vENDORFILEIDField;
            }
            set {
                this.vENDORFILEIDField = value;
                this.RaisePropertyChanged("VENDORFILEID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestDeleteAttach : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseResultNew : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool rESULTField;
        
        private string rESULTCODEField;
        
        private string rESULTMESSAGEField;
        
        private int rESULTDOSYAIDField;
        
        private string rESULTATTACHFILENAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool RESULT {
            get {
                return this.rESULTField;
            }
            set {
                this.rESULTField = value;
                this.RaisePropertyChanged("RESULT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RESULTCODE {
            get {
                return this.rESULTCODEField;
            }
            set {
                this.rESULTCODEField = value;
                this.RaisePropertyChanged("RESULTCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RESULTMESSAGE {
            get {
                return this.rESULTMESSAGEField;
            }
            set {
                this.rESULTMESSAGEField = value;
                this.RaisePropertyChanged("RESULTMESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int RESULTDOSYAID {
            get {
                return this.rESULTDOSYAIDField;
            }
            set {
                this.rESULTDOSYAIDField = value;
                this.RaisePropertyChanged("RESULTDOSYAID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RESULTATTACHFILENAME {
            get {
                return this.rESULTATTACHFILENAMEField;
            }
            set {
                this.rESULTATTACHFILENAMEField = value;
                this.RaisePropertyChanged("RESULTATTACHFILENAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestAttachSaveFOLDER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bILDIRIMNOField;
        
        private byte[] aTTACHField;
        
        private int aTTACHFILESIZEField;
        
        private string aTTACHFILENAMEField;
        
        private string aTTACHFILECONTENTTYPEField;
        
        private System.DateTime rECORD_DATEField;
        
        private string oRJINALFILENAMEField;
        
        private bool iSCONTROLField;
        
        private string aTTACHDESCRIPTIONField;
        
        private ApplicationName aPPLICATIONNAMEField;
        
        private string cREATEDUSERField;
        
        private string vENDORFILECODEField;
        
        private string bULKTRANSFER_CODEField;
        
        private bool bULKTRANSFERField;
        
        private string bULKTRANSFER_URLField;
        
        private string bASE64DATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BILDIRIMNO {
            get {
                return this.bILDIRIMNOField;
            }
            set {
                this.bILDIRIMNOField = value;
                this.RaisePropertyChanged("BILDIRIMNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ATTACH {
            get {
                return this.aTTACHField;
            }
            set {
                this.aTTACHField = value;
                this.RaisePropertyChanged("ATTACH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ATTACHFILESIZE {
            get {
                return this.aTTACHFILESIZEField;
            }
            set {
                this.aTTACHFILESIZEField = value;
                this.RaisePropertyChanged("ATTACHFILESIZE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ATTACHFILENAME {
            get {
                return this.aTTACHFILENAMEField;
            }
            set {
                this.aTTACHFILENAMEField = value;
                this.RaisePropertyChanged("ATTACHFILENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ATTACHFILECONTENTTYPE {
            get {
                return this.aTTACHFILECONTENTTYPEField;
            }
            set {
                this.aTTACHFILECONTENTTYPEField = value;
                this.RaisePropertyChanged("ATTACHFILECONTENTTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime RECORD_DATE {
            get {
                return this.rECORD_DATEField;
            }
            set {
                this.rECORD_DATEField = value;
                this.RaisePropertyChanged("RECORD_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ORJINALFILENAME {
            get {
                return this.oRJINALFILENAMEField;
            }
            set {
                this.oRJINALFILENAMEField = value;
                this.RaisePropertyChanged("ORJINALFILENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool ISCONTROL {
            get {
                return this.iSCONTROLField;
            }
            set {
                this.iSCONTROLField = value;
                this.RaisePropertyChanged("ISCONTROL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ATTACHDESCRIPTION {
            get {
                return this.aTTACHDESCRIPTIONField;
            }
            set {
                this.aTTACHDESCRIPTIONField = value;
                this.RaisePropertyChanged("ATTACHDESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public ApplicationName APPLICATIONNAME {
            get {
                return this.aPPLICATIONNAMEField;
            }
            set {
                this.aPPLICATIONNAMEField = value;
                this.RaisePropertyChanged("APPLICATIONNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CREATEDUSER {
            get {
                return this.cREATEDUSERField;
            }
            set {
                this.cREATEDUSERField = value;
                this.RaisePropertyChanged("CREATEDUSER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string VENDORFILECODE {
            get {
                return this.vENDORFILECODEField;
            }
            set {
                this.vENDORFILECODEField = value;
                this.RaisePropertyChanged("VENDORFILECODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string BULKTRANSFER_CODE {
            get {
                return this.bULKTRANSFER_CODEField;
            }
            set {
                this.bULKTRANSFER_CODEField = value;
                this.RaisePropertyChanged("BULKTRANSFER_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool BULKTRANSFER {
            get {
                return this.bULKTRANSFERField;
            }
            set {
                this.bULKTRANSFERField = value;
                this.RaisePropertyChanged("BULKTRANSFER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string BULKTRANSFER_URL {
            get {
                return this.bULKTRANSFER_URLField;
            }
            set {
                this.bULKTRANSFER_URLField = value;
                this.RaisePropertyChanged("BULKTRANSFER_URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string BASE64DATA {
            get {
                return this.bASE64DATAField;
            }
            set {
                this.bASE64DATAField = value;
                this.RaisePropertyChanged("BASE64DATA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ApplicationName {
        
        /// <remarks/>
        TEKNODESK,
        
        /// <remarks/>
        TEKNODESKSAP,
        
        /// <remarks/>
        ISTAKIP,
        
        /// <remarks/>
        TEKNOSTOK_ONARIM,
        
        /// <remarks/>
        TEKNOSERVIS,
        
        /// <remarks/>
        TEKNOSAHA,
        
        /// <remarks/>
        ISTAKIPSAPRAPOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AttachInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string bILDIRIMNOField;
        
        private string aTTACH_URLField;
        
        private int aTTACHFILESIZEField;
        
        private string aTTACHFILENAMEField;
        
        private string aTTACHFILECONTENTTYPEField;
        
        private System.DateTime rECORD_DATEField;
        
        private string oRJINALFILENAMEField;
        
        private bool iSCONTROLField;
        
        private string aTTACHDESCRIPTIONField;
        
        private string aTTACHFILENAMEDESCRIPTIONField;
        
        private string aTTACHFILENAMECODEField;
        
        private byte[] aTTACHDATAField;
        
        private string aPPLICATIONNAMEField;
        
        private string cREATEDUSERField;
        
        private string vENDORFILECODEField;
        
        private string bULKTRANSFER_CODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BILDIRIMNO {
            get {
                return this.bILDIRIMNOField;
            }
            set {
                this.bILDIRIMNOField = value;
                this.RaisePropertyChanged("BILDIRIMNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ATTACH_URL {
            get {
                return this.aTTACH_URLField;
            }
            set {
                this.aTTACH_URLField = value;
                this.RaisePropertyChanged("ATTACH_URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ATTACHFILESIZE {
            get {
                return this.aTTACHFILESIZEField;
            }
            set {
                this.aTTACHFILESIZEField = value;
                this.RaisePropertyChanged("ATTACHFILESIZE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ATTACHFILENAME {
            get {
                return this.aTTACHFILENAMEField;
            }
            set {
                this.aTTACHFILENAMEField = value;
                this.RaisePropertyChanged("ATTACHFILENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ATTACHFILECONTENTTYPE {
            get {
                return this.aTTACHFILECONTENTTYPEField;
            }
            set {
                this.aTTACHFILECONTENTTYPEField = value;
                this.RaisePropertyChanged("ATTACHFILECONTENTTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime RECORD_DATE {
            get {
                return this.rECORD_DATEField;
            }
            set {
                this.rECORD_DATEField = value;
                this.RaisePropertyChanged("RECORD_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ORJINALFILENAME {
            get {
                return this.oRJINALFILENAMEField;
            }
            set {
                this.oRJINALFILENAMEField = value;
                this.RaisePropertyChanged("ORJINALFILENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool ISCONTROL {
            get {
                return this.iSCONTROLField;
            }
            set {
                this.iSCONTROLField = value;
                this.RaisePropertyChanged("ISCONTROL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ATTACHDESCRIPTION {
            get {
                return this.aTTACHDESCRIPTIONField;
            }
            set {
                this.aTTACHDESCRIPTIONField = value;
                this.RaisePropertyChanged("ATTACHDESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ATTACHFILENAMEDESCRIPTION {
            get {
                return this.aTTACHFILENAMEDESCRIPTIONField;
            }
            set {
                this.aTTACHFILENAMEDESCRIPTIONField = value;
                this.RaisePropertyChanged("ATTACHFILENAMEDESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ATTACHFILENAMECODE {
            get {
                return this.aTTACHFILENAMECODEField;
            }
            set {
                this.aTTACHFILENAMECODEField = value;
                this.RaisePropertyChanged("ATTACHFILENAMECODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=12)]
        public byte[] ATTACHDATA {
            get {
                return this.aTTACHDATAField;
            }
            set {
                this.aTTACHDATAField = value;
                this.RaisePropertyChanged("ATTACHDATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string APPLICATIONNAME {
            get {
                return this.aPPLICATIONNAMEField;
            }
            set {
                this.aPPLICATIONNAMEField = value;
                this.RaisePropertyChanged("APPLICATIONNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CREATEDUSER {
            get {
                return this.cREATEDUSERField;
            }
            set {
                this.cREATEDUSERField = value;
                this.RaisePropertyChanged("CREATEDUSER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string VENDORFILECODE {
            get {
                return this.vENDORFILECODEField;
            }
            set {
                this.vENDORFILECODEField = value;
                this.RaisePropertyChanged("VENDORFILECODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string BULKTRANSFER_CODE {
            get {
                return this.bULKTRANSFER_CODEField;
            }
            set {
                this.bULKTRANSFER_CODEField = value;
                this.RaisePropertyChanged("BULKTRANSFER_CODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool rESULTField;
        
        private string rESULTCODEField;
        
        private string rESULTMESSAGEField;
        
        private AttachInformation[] aTTACHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool RESULT {
            get {
                return this.rESULTField;
            }
            set {
                this.rESULTField = value;
                this.RaisePropertyChanged("RESULT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RESULTCODE {
            get {
                return this.rESULTCODEField;
            }
            set {
                this.rESULTCODEField = value;
                this.RaisePropertyChanged("RESULTCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RESULTMESSAGE {
            get {
                return this.rESULTMESSAGEField;
            }
            set {
                this.rESULTMESSAGEField = value;
                this.RaisePropertyChanged("RESULTMESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public AttachInformation[] ATTACH {
            get {
                return this.aTTACHField;
            }
            set {
                this.aTTACHField = value;
                this.RaisePropertyChanged("ATTACH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TeknoserDosyaAktarimSoapChannel : MultiFileUploadTest.DosyAAktarim.TeknoserDosyaAktarimSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeknoserDosyaAktarimSoapClient : System.ServiceModel.ClientBase<MultiFileUploadTest.DosyAAktarim.TeknoserDosyaAktarimSoap>, MultiFileUploadTest.DosyAAktarim.TeknoserDosyaAktarimSoap {
        
        public TeknoserDosyaAktarimSoapClient() {
        }
        
        public TeknoserDosyaAktarimSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeknoserDosyaAktarimSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeknoserDosyaAktarimSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeknoserDosyaAktarimSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResult ATTACHSAVE(MultiFileUploadTest.DosyAAktarim.RequestAttachSave RequestAttachSave) {
            return base.Channel.ATTACHSAVE(RequestAttachSave);
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResult ATTACHSAVEFOLDER(MultiFileUploadTest.DosyAAktarim.RequestAttachSaveFOLDER RequestAttachSave) {
            return base.Channel.ATTACHSAVEFOLDER(RequestAttachSave);
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResultNew ATTACHSAVEFOLDER_NEW(MultiFileUploadTest.DosyAAktarim.RequestAttachSaveFOLDER RequestAttachSave) {
            return base.Channel.ATTACHSAVEFOLDER_NEW(RequestAttachSave);
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResultNew ATTACHSAVEFOLDER_NEW_PILOT(MultiFileUploadTest.DosyAAktarim.RequestAttachSaveFOLDER RequestAttachSave) {
            return base.Channel.ATTACHSAVEFOLDER_NEW_PILOT(RequestAttachSave);
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResult DELETEATTACH(MultiFileUploadTest.DosyAAktarim.RequestDeleteAttach RequestDeleteAttach) {
            return base.Channel.DELETEATTACH(RequestDeleteAttach);
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResult MOBILEPRINTINFOREOPEN(string BILDIRIMNO) {
            return base.Channel.MOBILEPRINTINFOREOPEN(BILDIRIMNO);
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResult UPDATEVENDORFILEID(MultiFileUploadTest.DosyAAktarim.RequestUPDATEVENDORFILEID RequestUPDATEVENDORFILEID) {
            return base.Channel.UPDATEVENDORFILEID(RequestUPDATEVENDORFILEID);
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResult DELETEATTACH_BILDIRIMNO_AND_DOSYATIPI(MultiFileUploadTest.DosyAAktarim.RequestDeleteBildirimAndDosyaTipi RequestDeleteBildirimAndDosyaTipi) {
            return base.Channel.DELETEATTACH_BILDIRIMNO_AND_DOSYATIPI(RequestDeleteBildirimAndDosyaTipi);
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResult GETATTACHIMAGE(MultiFileUploadTest.DosyAAktarim.RequestAttachImage RequestAttachImage) {
            return base.Channel.GETATTACHIMAGE(RequestAttachImage);
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResult GETATTACH(MultiFileUploadTest.DosyAAktarim.RequestGetAttach RequestGetAttach) {
            return base.Channel.GETATTACH(RequestGetAttach);
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResult GETATTACHBULKCODE(MultiFileUploadTest.DosyAAktarim.RequestGetAttachBulkCode RequestGetAttach) {
            return base.Channel.GETATTACHBULKCODE(RequestGetAttach);
        }
        
        public bool UPDATEFILECOUNT(string _ApplicationName, string BILDIRIMNO) {
            return base.Channel.UPDATEFILECOUNT(_ApplicationName, BILDIRIMNO);
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResult ING_ATTACHSAVEFOLDER(MultiFileUploadTest.DosyAAktarim.RequestAttachSaveFOLDER RequestAttachSave) {
            return base.Channel.ING_ATTACHSAVEFOLDER(RequestAttachSave);
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResult ING_DELETEATTACH(MultiFileUploadTest.DosyAAktarim.RequestDeleteAttach RequestDeleteAttach) {
            return base.Channel.ING_DELETEATTACH(RequestDeleteAttach);
        }
        
        public MultiFileUploadTest.DosyAAktarim.ResponseResult ING_GETATTACHIMAGE(MultiFileUploadTest.DosyAAktarim.RequestAttachImage RequestAttachImage) {
            return base.Channel.ING_GETATTACHIMAGE(RequestAttachImage);
        }
    }
}
